In [1]:
import numpy as np

In [3]:
a = np.array(np.random.randint(1, 100, (3, 4)))

In [4]:
a

array([[95, 93, 99, 68],
       [80, 28,  5, 30],
       [44, 93, 67, 42]])

In [5]:
a.ravel()

array([95, 93, 99, 68, 80, 28,  5, 30, 44, 93, 67, 42])

In [6]:
a

array([[95, 93, 99, 68],
       [80, 28,  5, 30],
       [44, 93, 67, 42]])

In [7]:
a.flatten()

array([95, 93, 99, 68, 80, 28,  5, 30, 44, 93, 67, 42])

In [8]:
a

array([[95, 93, 99, 68],
       [80, 28,  5, 30],
       [44, 93, 67, 42]])